apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: default
spec:
  selector:
    app: demo-app
    version: green  # Initially points to blue
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: LoadBalancer
